modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="floatingdoors"
version="1.0.0"
displayName="Floating Doors"
authors="Guille"
description='''
Makes doors float: breaking the block under a door no longer breaks the door.

[[mixins]]
config = "floatingdoors.mixins.json"
'''
